services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - '992'
    devices:
      - /dev/dri:/dev/dri
    # network_mode: 'host'
    volumes:
      - ~/homelab/data/jellyfin/config:/config
      - ~/homelab/data/jellyfin/cache:/cache
      - type: bind
        source: ~/Exchange
        target: /Exchange
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    restart: 'unless-stopped'
    ports:
      - 8096:8096
      - 7359:7359
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
